name: CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          cache: true
          go-version-file: "go.mod"

      - name: Get dependencies
        run: go mod download

      - name: Lint
        run: make lint

      - name: Build
        run: make bin
